# Copyright 2024 - 2025 Crunchy Data Solutions, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates
# schema documentation: https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
---
version: 2
updates:
  # Update all workflows and local composite actions.
  - package-ecosystem: github-actions
    directories:
      # "/" is a special case that includes ".github/workflows/*"
      - '/'
      - '.github/actions/*'
    schedule:
      interval: weekly
      day: tuesday
    groups:
      all-github-actions:
        patterns: ['*']

  # Go "x" modules and Go and Google gRPC modules:
  # https://pkg.go.dev/golang.org/x
  # https://cloud.google.com/go/google.golang.org
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: wednesday
    groups:
      golang-org-modules:
        patterns:
          - 'golang.org/x/*'
          - 'github.com/golang/*'
          - 'google.golang.org/*'
