---
# Create a cluster and wait for it and its primary Service to be ready.
apiVersion: testing/v1
kind: Step
resources:
- apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    name: cluster-start
  spec:
    postgresVersion: 14
    instances:
    - name: instance1
      dataVolumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }
    backups:
      pgbackrest:
        repos:
        - name: repo1
          volume:
            volumeClaimSpec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 1Gi } } }

asserts:
- apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    name: cluster-start
  status:
    instances:
    - name: instance1
      replicas: 1
      readyReplicas: 1
      updatedReplicas: 1

- apiVersion: v1
  kind: Service
  metadata:
    name: cluster-start-primary

---
# Run a job that connects through the primary service.
apiVersion: testing/v1
kind: Step
resources:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: psql-connect
  spec:
    template:
      spec:
        restartPolicy: OnFailure
        containers:
        - name: psql
          image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.1-1
          command:
            - psql
            - -c
            - select version();
          env:
          - name: PGHOST
            valueFrom: { secretKeyRef: { name: cluster-start-pguser-cluster-start, key: host } }
          - name: PGPORT
            valueFrom: { secretKeyRef: { name: cluster-start-pguser-cluster-start, key: port } }
          - name: PGDATABASE
            valueFrom: { secretKeyRef: { name: cluster-start-pguser-cluster-start, key: dbname } }
          - name: PGUSER
            valueFrom: { secretKeyRef: { name: cluster-start-pguser-cluster-start, key: user } }
          - name: PGPASSWORD
            valueFrom: { secretKeyRef: { name: cluster-start-pguser-cluster-start, key: password } }

asserts:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: psql-connect
  status:
    succeeded: 1
