on:
  pull_request:
    branches:
      - savannah

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
          args: --timeout=5m
          only-new-issues: true

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://docker.io/hadolint/hadolint
        with:
          args: hadolint build/*/Dockerfile

